min_expl_english_text = {
     'has_prior_history_of_violation' : 'the aircraft operator should have a prior history of violations',
     'not(has_prior_history_of_violation)' : 'the aircraft operator should not have a prior history of violations',
     'max_takeoff_weight' : 'the aircraft should have a maximum takeoff weight greater than  55 pounds',
    'not(max_takeoff_weight)' : 'the aircraft should have a maximum takeoff weight less than or equal to 55 pounds',
     'aircrafts_nearby' : 'there should be aircrafts flying nearby', 
     'not(aircrafts_nearby)' : 'there should not be any aircrafts flying nearby', 
     'yield_right_of_way' : 'the aircraft should yielded right of way to all nearby aircrafts',
     'not(yield_right_of_way)' : 'the aircraft should not yield right of way to nearby aircrafts',
     'used_spotted' : 'the operator should use a spotter',
     'not(used_spotted)' : 'the operator should not use a spotter',
     'flew_above_400_ft' : 'the aircraft should fly above 400 feet',
     'not(flew_above_400_ft)' : 'the aircraft should not fly above 400 feet',
     'within_3_miles' : 'the aircraft should be within 3 miles of the airport',
     'not(within_3_miles)' : 'the aircraft shoud be farther than 3 miles of the airport',
     'notify_authority' : 'the operator should notify authorities',
     'not(notify_authority)' : 'the operator should not notified authorities',
     'expert_assistance' : 'the operator should have expert assistance',
     'not(expert_assistance)' : 'the operator should not have any expert assistance',
    'flown_under_ama_rules' : 'the aircraft should be flown according to AMA rules',
    'not(flown_under_ama_rules)' : 'the aircraft should not be flown according to AMA rules',
    'flown_in_sanctioned_show' : 'the aircraft should be flown in a sanctioned show',
    'not(flown_in_sanctioned_show)' : 'the aricraft should not be flown in a sanctiooned show',
    'maneuvers_established_beforehand' : 'all aircraft manuevers should be established beforehand',
    'not(manuevers_established_beforehand' : 'aircraft manuevers should  not be established beforehand',
    'has_name_address' : 'the aircraft operator should provide a name and address',
    'not(has_name_address)' : 'the aircraft should not have an operator name or address',
    'flown_indoors' : 'the aircraft should be flown only indoors',
    'not(flown_indoors)' : 'the aircraft should not be flown outdoors',
    'address_affixed' : 'the aircraft should have an address affixed',
    'not(address_affixed)' : 'the aircraft should have no address affixed',
    'has_metal_blade_rollers' : 'the aircraft should have metal blade rollers',
    'not(has_metal_blade_rollers)' : 'the aircraft should not have metal blade rollers',
    'carries_pyrotechnic_devices' : 'the aircraft should carry pyrotechnic devices',
    'not(carries_pyrotechnic_devices)' : 'the aircraft should not carry any pyrotechnic device',
    'devices_produce_smoke_when_burnt' : 'the pyrotechnique devices should produce smoke when burnt',
    'not(devices_produce_smoke_when_burnt)' : 'the pyrotechnique devices should not produce smoke when burnt',
    'devices_securely_attached' : 'the devices should be securely attached',
    'not(devices_securely_attached)' : 'the devices should not be securely attached',
    'g_series_rocket_motors' : 'the pyrotechinque devices should be of G Series Rocket Motors class',
    'not(g_series_rocket_motors)' : 'the pyrotechnique devices should not be of G Series class',
    'g_series_firmly_attached' : 'the G Series motors should be firmly attached',
    'not(g_series_fimrly_attached)' : 'the G Series motors should not be firmly attached',
    'air_show_team_ama_compliant' : 'the aircraft team should be an officially designated AMA Airshow team',
    'not(air_show_team_ama_compliant)' : 'the aircraft team should not be an official designated AMA Airshow team',
    'alcohol_drug_influence' : 'the operator should be under the influence of alcohol or drugs',
    'not(alcohol_druc_influence)' : 'the operator should not be under the influence of alcohol or drugs',
    'helmets_worn' : 'the operator should wear a helmet',
    'not(helmets_worn)' : 'the operator should not wear a helmet',
    'osha_approved' : 'the helmets worn should be OSHA/DOT/ANSI/SNELL/NOCSAE approved',
    'not(osha_approved)' : 'the helmets worn should not be OSHA/DOT/ANSI/SNELL/NOCSAE approved',
    'helmets_under_comparable_standards' : 'the helmets should be compliant with comparable standards',
    'not(helmets_under_comparable_standards)' : 'the helmets should not compliant be with comparable standards'
     };